### ISSUE TITLE
bạn cho mình hỏi với?

### ISSUE THREAD

**Issue by barttran2k** [trongtuyen99/viet_summarizer#1]
Cho mình xin email hay fb cho dễ liên hệ được không?

**Comment by trongtuyen99** [comment]
Đây bạn nhé: Tuyen Dam | Facebook
<https://www.facebook.com/tuyen.dam.31149/>

Vào Th 6, 12 thg 11, 2021 vào lúc 15:45 Trần Cao Minh Bách <
***@***.***> đã viết:
